/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarCatalog;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TILAK PARMAR
 */
public class AllAvailableCarsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AllAvailableCarsJPanel
     */
    private CarCatalog carslist;
    private JPanel userProcessContainer;
    private ArrayList<Car> tempAvCars;
    private ArrayList<Car> tempNotAvCars;
    
    public AllAvailableCarsJPanel(JPanel userProcessContainer, CarCatalog carslist) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.carslist=carslist;
        
        tempAvCars = new ArrayList<>();
        tempNotAvCars = new ArrayList<>();
                
        populateAvailableTable();
        populateNotAvailableTable();
    }
    
    public void populateAvailableTable(){
        for(Car c : CarCatalog.getCarList())
        {
            if(c.isAvailable())
                tempAvCars.add(c);
        }
        
        DefaultTableModel dtm = (DefaultTableModel)tblAvailableCars.getModel();
        dtm.setRowCount(0);
        for (Car car: tempAvCars){
            Object[] row = new Object[8];
            row[0]=car;
            row[1]=car.getBrand();
            if(car.isAvailable())
                row[2]="Yes";
            else
                row[2]="No";
            row[3]=car.getModel_num();
            row[4]=car.getManufactured_year();
            row[5]=car.getAvailble_city();
            row[6]=car.getMin_seats();
            row[7]=car.getMax_seats();
            dtm.addRow(row);
        }
    }
    
    public void populateNotAvailableTable(){
        for(Car c : CarCatalog.getCarList())
        {
            if(c.isAvailable()==false)
                tempNotAvCars.add(c);
        }
        
        DefaultTableModel dtm = (DefaultTableModel)tblNotAvailableCars.getModel();
        dtm.setRowCount(0);
        for (Car car: tempNotAvCars){
            Object[] row = new Object[8];
            row[0]=car;
            row[1]=car.getBrand();
            if(car.isAvailable())
                row[2]="Yes";
            else
                row[2]="No";
            row[3]=car.getModel_num();
            row[4]=car.getManufactured_year();
            row[5]=car.getAvailble_city();
            row[6]=car.getMin_seats();
            row[7]=car.getMax_seats();
            dtm.addRow(row);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAvailableCars = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        TextFieldSeatSearch = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNotAvailableCars = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        btnBack.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblAvailableCars.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tblAvailableCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr. No.", "Brand", "Available", "Model No.", "Year", "City", "Min Seats", "Max Seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAvailableCars);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Available Cars");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Not Available Cars");

        btnSearch.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        TextFieldSeatSearch.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        TextFieldSeatSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldSeatSearchActionPerformed(evt);
            }
        });

        tblNotAvailableCars.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tblNotAvailableCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr. No.", "Brand", "Available", "Model No.", "Year", "City", "Min Seats", "Max Seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblNotAvailableCars);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Search Available Cars by City:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldSeatSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldSeatSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void TextFieldSeatSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldSeatSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldSeatSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)tblAvailableCars.getModel();
        dtm.setRowCount(0);
        for (Car car: tempAvCars){
            Object[] row = new Object[8];
            row[0]=car;
            row[1]=car.getBrand();
            if(car.isAvailable())
                row[2]="Yes";
            else
                row[2]="No";
            row[3]=car.getModel_num();
            row[4]=car.getManufactured_year();
            row[5]=car.getAvailble_city();
            row[6]=car.getMin_seats();
            row[7]=car.getMax_seats();
            if (car.getAvailble_city().equalsIgnoreCase(TextFieldSeatSearch.getText()))
                dtm.addRow(row);
        }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldSeatSearch;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblAvailableCars;
    private javax.swing.JTable tblNotAvailableCars;
    // End of variables declaration//GEN-END:variables
}
