/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarCatalog;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author TILAK PARMAR
 */
public class CreateCarJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateCarJPanel
     */
    private JPanel userProcessContainer;
    private CarCatalog carList;
    ButtonGroup bgroupAvail;
    ButtonGroup bgroupMainCerti;
    public CreateCarJPanel(JPanel userProcessContainer, CarCatalog carList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.carList = carList;
        
        bgroupAvail = new ButtonGroup();
        bgroupAvail.add(RadioYes);
        bgroupAvail.add(RadioNo);
        
        bgroupMainCerti = new ButtonGroup();
        bgroupMainCerti.add(RadioExpired);
        bgroupMainCerti.add(RadioNotExpired);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextFieldBrand = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TextFieldModelNo = new javax.swing.JTextField();
        TextFieldYear = new javax.swing.JTextField();
        TextFieldMinSeats = new javax.swing.JTextField();
        TextFieldMaxSeats = new javax.swing.JTextField();
        TextFieldSerialNo = new javax.swing.JTextField();
        TextFieldCity = new javax.swing.JTextField();
        RadioYes = new javax.swing.JRadioButton();
        RadioNo = new javax.swing.JRadioButton();
        RadioExpired = new javax.swing.JRadioButton();
        RadioNotExpired = new javax.swing.JRadioButton();
        btnRegister = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register Your Car for Uber");

        btnBack.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Brand:*");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Model Number:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Manufactured In (Year):*");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Max Seats:*");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Min Seats:*");

        TextFieldBrand.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Is Your Car Available?:*");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("City:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Maintainence Certificate:*");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Serial Number:*");

        TextFieldModelNo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        TextFieldYear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        TextFieldMinSeats.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        TextFieldMaxSeats.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        TextFieldSerialNo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        TextFieldCity.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        RadioYes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        RadioYes.setText("Yes");

        RadioNo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        RadioNo.setText("No");

        RadioExpired.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        RadioExpired.setText("Expired");

        RadioNotExpired.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        RadioNotExpired.setText("Not Expired");

        btnRegister.setBackground(new java.awt.Color(255, 255, 255));
        btnRegister.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldBrand))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(TextFieldModelNo))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(TextFieldYear))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(TextFieldMinSeats))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(TextFieldMaxSeats))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(TextFieldSerialNo))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(TextFieldCity))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RadioYes)
                                .addGap(18, 18, 18)
                                .addComponent(RadioNo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RadioExpired)
                                        .addGap(18, 18, 18)
                                        .addComponent(RadioNotExpired))
                                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(TextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(TextFieldModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addComponent(TextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addComponent(TextFieldMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(TextFieldMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RadioYes)
                        .addComponent(RadioNo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10))
                    .addComponent(TextFieldSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addComponent(TextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RadioExpired)
                        .addComponent(RadioNotExpired)))
                .addGap(18, 18, 18)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        
        String brand = TextFieldBrand.getText();
        if (brand == null || brand.equals("")){
            JOptionPane.showMessageDialog(null, "Brand Name can't be empty!");
            return;
        }
        
        String manufactured_year = TextFieldYear.getText();
        if(manufactured_year.length()!=4){
            JOptionPane.showMessageDialog(null, "Enter Year in YYYY format.");
            return;
        }
            
        try{
             Integer.parseInt(manufactured_year);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please type an Year!");
            return;
        }
        
        String min_seats = TextFieldMinSeats.getText();
        try{
             Integer.parseInt(min_seats);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter a number for Minimum Seats!");
            return;
        }
        if(Integer.parseInt(min_seats)>10 || Integer.parseInt(min_seats)<0){
            JOptionPane.showMessageDialog(null, "Minimum Seats should be between 0 and 10");
            return;
        }
        
        String max_seats = TextFieldMaxSeats.getText();
        try{
             Integer.parseInt(max_seats);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter a number for Maximum Seats!");
            return;
        }
        if(Integer.parseInt(max_seats) < Integer.parseInt(min_seats)){
            JOptionPane.showMessageDialog(null, "Maximum Seats cannot be less than Minimum seats!");
            return;
        }
        if(Integer.parseInt(max_seats)>10 || Integer.parseInt(max_seats)<0){
            JOptionPane.showMessageDialog(null, "Maximum Seats should be between 0 and 10.");
            return;
        }
        
        String serial_num = TextFieldSerialNo.getText();
        try{
             Integer.parseInt(serial_num);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter a number in Sr. No.!");
            return;
        }
        
        if(RadioYes.isSelected()==false && RadioNo.isSelected()==false)
        {
            JOptionPane.showMessageDialog(null, "Please select Availability of your Car");
            return;
        }
        boolean available = RadioYes.isSelected();
        
        
        if(RadioExpired.isSelected()==false && RadioNotExpired.isSelected()==false)
        {
            JOptionPane.showMessageDialog(null, "Please select the Status of your car's Maintainence Certificate");
            return;
        }
        boolean maintenance_certificate = RadioNotExpired.isSelected();
        
        String model_num = TextFieldModelNo.getText();
        String availble_city = TextFieldCity.getText();
        
        Car car = CarCatalog.addCar(available, brand, Integer.parseInt(manufactured_year), Integer.parseInt(min_seats), Integer.parseInt(max_seats), Integer.parseInt(serial_num), model_num, availble_city, maintenance_certificate);
        carList.setFleetUpdate(new Date());
        
        JOptionPane.showMessageDialog(null, "Car Registered Successfully!");
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioExpired;
    private javax.swing.JRadioButton RadioNo;
    private javax.swing.JRadioButton RadioNotExpired;
    private javax.swing.JRadioButton RadioYes;
    private javax.swing.JTextField TextFieldBrand;
    private javax.swing.JTextField TextFieldCity;
    private javax.swing.JTextField TextFieldMaxSeats;
    private javax.swing.JTextField TextFieldMinSeats;
    private javax.swing.JTextField TextFieldModelNo;
    private javax.swing.JTextField TextFieldSerialNo;
    private javax.swing.JTextField TextFieldYear;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
