/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarCatalog;
import static Business.CarCatalog.carList;
import java.awt.CardLayout;
import java.util.HashSet;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author TILAK PARMAR
 */
public class SearchOptionsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AppManagementJPanel
     */
    private JPanel userProcessContainer;
    private CarCatalog carslist;
    public SearchOptionsJPanel(JPanel userProcessContainer, CarCatalog carslist) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.carslist=carslist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1firstcar = new javax.swing.JButton();
        btn2AllAvailable = new javax.swing.JButton();
        btn3EnableManufacturers = new javax.swing.JButton();
        btn4EnableYear = new javax.swing.JButton();
        btn5EnableSeats = new javax.swing.JButton();
        btn6EnableSerialNo = new javax.swing.JButton();
        btn7EnableModel = new javax.swing.JButton();
        btn8AllManuf = new javax.swing.JButton();
        btn9FleetUpdate = new javax.swing.JButton();
        btn10EnableCity = new javax.swing.JButton();
        btn11ExpiredMC = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        label1firstcar = new javax.swing.JLabel();
        TextField5MaxSeats = new javax.swing.JTextField();
        btn5SearchSeats = new javax.swing.JButton();
        TextField4year = new javax.swing.JTextField();
        btn4SearchYear = new javax.swing.JButton();
        TextField3Manufacturers = new javax.swing.JTextField();
        btn3SearchManufacturers = new javax.swing.JButton();
        btn7SearchModel = new javax.swing.JButton();
        TextField7model = new javax.swing.JTextField();
        TextField10City = new javax.swing.JTextField();
        btn10SearchCity = new javax.swing.JButton();
        label6SerialNo = new javax.swing.JLabel();
        btn6SearchSerialNo = new javax.swing.JButton();
        TextField6SerialNo = new javax.swing.JTextField();
        labelFleetUpdate = new javax.swing.JLabel();
        label8AllManufacturers = new javax.swing.JLabel();
        TextField5MinSeats = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        btn1firstcar.setBackground(new java.awt.Color(255, 255, 255));
        btn1firstcar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn1firstcar.setText("1. First Available Passenger Car");
        btn1firstcar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn1firstcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1firstcarActionPerformed(evt);
            }
        });

        btn2AllAvailable.setBackground(new java.awt.Color(255, 255, 255));
        btn2AllAvailable.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn2AllAvailable.setText("2. All Available/Not Available Cars");
        btn2AllAvailable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn2AllAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2AllAvailableActionPerformed(evt);
            }
        });

        btn3EnableManufacturers.setBackground(new java.awt.Color(255, 255, 255));
        btn3EnableManufacturers.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn3EnableManufacturers.setText("3. Cars made by Specific Manufacturers");
        btn3EnableManufacturers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn3EnableManufacturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3EnableManufacturersActionPerformed(evt);
            }
        });

        btn4EnableYear.setBackground(new java.awt.Color(255, 255, 255));
        btn4EnableYear.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn4EnableYear.setText("4. Cars made in a Specific Year");
        btn4EnableYear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn4EnableYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4EnableYearActionPerformed(evt);
            }
        });

        btn5EnableSeats.setBackground(new java.awt.Color(255, 255, 255));
        btn5EnableSeats.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn5EnableSeats.setText("5. Find Available Cars as per Required Seats");
        btn5EnableSeats.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn5EnableSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5EnableSeatsActionPerformed(evt);
            }
        });

        btn6EnableSerialNo.setBackground(new java.awt.Color(255, 255, 255));
        btn6EnableSerialNo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn6EnableSerialNo.setText("6. Find Car from its Serial Number");
        btn6EnableSerialNo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn6EnableSerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6EnableSerialNoActionPerformed(evt);
            }
        });

        btn7EnableModel.setBackground(new java.awt.Color(255, 255, 255));
        btn7EnableModel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn7EnableModel.setText("7. List of all Cars with Specific Model No.");
        btn7EnableModel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn7EnableModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7EnableModelActionPerformed(evt);
            }
        });

        btn8AllManuf.setBackground(new java.awt.Color(255, 255, 255));
        btn8AllManuf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn8AllManuf.setText("8. List of All Car Manufacturers");
        btn8AllManuf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn8AllManuf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8AllManufActionPerformed(evt);
            }
        });

        btn9FleetUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btn9FleetUpdate.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn9FleetUpdate.setText("9. Last Fleet Catalog Updated At:");
        btn9FleetUpdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn9FleetUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9FleetUpdateActionPerformed(evt);
            }
        });

        btn10EnableCity.setBackground(new java.awt.Color(255, 255, 255));
        btn10EnableCity.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn10EnableCity.setText("10. Cars Available in Specific City");
        btn10EnableCity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn10EnableCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10EnableCityActionPerformed(evt);
            }
        });

        btn11ExpiredMC.setBackground(new java.awt.Color(255, 255, 255));
        btn11ExpiredMC.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn11ExpiredMC.setText("11. Cars with Expired Maintainence Certificate");
        btn11ExpiredMC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn11ExpiredMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ExpiredMCActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        label1firstcar.setBackground(new java.awt.Color(255, 255, 255));
        label1firstcar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        TextField5MaxSeats.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        TextField5MaxSeats.setEnabled(false);
        TextField5MaxSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField5MaxSeatsActionPerformed(evt);
            }
        });

        btn5SearchSeats.setBackground(new java.awt.Color(255, 255, 255));
        btn5SearchSeats.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn5SearchSeats.setText("Search");
        btn5SearchSeats.setEnabled(false);
        btn5SearchSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5SearchSeatsActionPerformed(evt);
            }
        });

        TextField4year.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        TextField4year.setEnabled(false);
        TextField4year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField4yearActionPerformed(evt);
            }
        });

        btn4SearchYear.setBackground(new java.awt.Color(255, 255, 255));
        btn4SearchYear.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn4SearchYear.setText("Search");
        btn4SearchYear.setEnabled(false);
        btn4SearchYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4SearchYearActionPerformed(evt);
            }
        });

        TextField3Manufacturers.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        TextField3Manufacturers.setEnabled(false);
        TextField3Manufacturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField3ManufacturersActionPerformed(evt);
            }
        });

        btn3SearchManufacturers.setBackground(new java.awt.Color(255, 255, 255));
        btn3SearchManufacturers.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn3SearchManufacturers.setText("Search");
        btn3SearchManufacturers.setEnabled(false);
        btn3SearchManufacturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3SearchManufacturersActionPerformed(evt);
            }
        });

        btn7SearchModel.setBackground(new java.awt.Color(255, 255, 255));
        btn7SearchModel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn7SearchModel.setText("Search");
        btn7SearchModel.setEnabled(false);
        btn7SearchModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7SearchModelActionPerformed(evt);
            }
        });

        TextField7model.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        TextField7model.setEnabled(false);
        TextField7model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField7modelActionPerformed(evt);
            }
        });

        TextField10City.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        TextField10City.setEnabled(false);
        TextField10City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField10CityActionPerformed(evt);
            }
        });

        btn10SearchCity.setBackground(new java.awt.Color(255, 255, 255));
        btn10SearchCity.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn10SearchCity.setText("Search");
        btn10SearchCity.setEnabled(false);
        btn10SearchCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10SearchCityActionPerformed(evt);
            }
        });

        label6SerialNo.setBackground(new java.awt.Color(255, 255, 255));
        label6SerialNo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        btn6SearchSerialNo.setBackground(new java.awt.Color(255, 255, 255));
        btn6SearchSerialNo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn6SearchSerialNo.setText("Search");
        btn6SearchSerialNo.setEnabled(false);
        btn6SearchSerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6SearchSerialNoActionPerformed(evt);
            }
        });

        TextField6SerialNo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        TextField6SerialNo.setEnabled(false);
        TextField6SerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField6SerialNoActionPerformed(evt);
            }
        });

        labelFleetUpdate.setBackground(new java.awt.Color(255, 255, 255));
        labelFleetUpdate.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        label8AllManufacturers.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        TextField5MinSeats.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        TextField5MinSeats.setEnabled(false);
        TextField5MinSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField5MinSeatsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Min Seats:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Max Seats:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn1firstcar, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label1firstcar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn9FleetUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8AllManuf, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label8AllManufacturers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelFleetUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn6EnableSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TextField6SerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn6SearchSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label6SerialNo, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn10EnableCity, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TextField10City, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn10SearchCity, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn2AllAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn11ExpiredMC, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn7EnableModel, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TextField7model, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn7SearchModel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btn4EnableYear, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TextField4year))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btn3EnableManufacturers, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TextField3Manufacturers, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn3SearchManufacturers, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn4SearchYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn5EnableSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(TextField5MinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(TextField5MaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn5SearchSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn1firstcar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label1firstcar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn2AllAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn3EnableManufacturers, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField3Manufacturers, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3SearchManufacturers, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4EnableYear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField4year, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4SearchYear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn5EnableSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField5MaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5SearchSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextField5MinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn6EnableSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextField6SerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn6SearchSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn7EnableModel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField7model, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn7SearchModel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label6SerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label8AllManufacturers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn8AllManuf, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelFleetUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn9FleetUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn10EnableCity, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField10City, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10SearchCity, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn11ExpiredMC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn1firstcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1firstcarActionPerformed
        // TODO add your handling code here:
        TextField5MinSeats.setEnabled(false);
        TextField5MaxSeats.setEnabled(false);
        btn5SearchSeats.setEnabled(false);
        TextField3Manufacturers.setEnabled(false);
        btn3SearchManufacturers.setEnabled(false);
        TextField4year.setEnabled(false);
        btn4SearchYear.setEnabled(false);
        TextField7model.setEnabled(false);
        btn7SearchModel.setEnabled(false);
        TextField10City.setEnabled(false);
        btn10SearchCity.setEnabled(false);
        TextField6SerialNo.setEnabled(false);
        btn6SearchSerialNo.setEnabled(false);
        
        int i=0;
        for(Car car : carList){
            if(car.isAvailable()){
                label1firstcar.setText("Sr. No: " + car.getSerial_num() + "  |  Brand: " + car.getBrand() + "  |  Model: " + car.getModel_num() + "  |  City: " + car.getAvailble_city());
                break;
            }
        i++;
        }
        if(i>=carList.size())
            JOptionPane.showMessageDialog(null, "Sorry! No Cars Available");
        
    }//GEN-LAST:event_btn1firstcarActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void TextField5MaxSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField5MaxSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField5MaxSeatsActionPerformed

    private void TextField4yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField4yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField4yearActionPerformed

    private void TextField3ManufacturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField3ManufacturersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField3ManufacturersActionPerformed

    private void TextField7modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField7modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField7modelActionPerformed

    private void TextField10CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField10CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField10CityActionPerformed

    private void btn5EnableSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5EnableSeatsActionPerformed
        // TODO add your handling code here:
        TextField5MinSeats.setEnabled(true);
        TextField5MaxSeats.setEnabled(true);
        btn5SearchSeats.setEnabled(true);
        
        TextField3Manufacturers.setEnabled(false);
        btn3SearchManufacturers.setEnabled(false);
        TextField4year.setEnabled(false);
        btn4SearchYear.setEnabled(false);
        TextField7model.setEnabled(false);
        btn7SearchModel.setEnabled(false);
        TextField10City.setEnabled(false);
        btn10SearchCity.setEnabled(false);
        TextField6SerialNo.setEnabled(false);
        btn6SearchSerialNo.setEnabled(false);
    }//GEN-LAST:event_btn5EnableSeatsActionPerformed

    private void btn3EnableManufacturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3EnableManufacturersActionPerformed
        // TODO add your handling code here:
        TextField3Manufacturers.setEnabled(true);
        btn3SearchManufacturers.setEnabled(true);
        
        TextField5MaxSeats.setEnabled(false);
        TextField5MinSeats.setEnabled(false);
        btn5SearchSeats.setEnabled(false);
        TextField4year.setEnabled(false);
        btn4SearchYear.setEnabled(false);
        TextField7model.setEnabled(false);
        btn7SearchModel.setEnabled(false);
        TextField10City.setEnabled(false);
        btn10SearchCity.setEnabled(false);
        TextField6SerialNo.setEnabled(false);
        btn6SearchSerialNo.setEnabled(false);
    }//GEN-LAST:event_btn3EnableManufacturersActionPerformed

    private void btn4EnableYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4EnableYearActionPerformed
        // TODO add your handling code here:
        TextField4year.setEnabled(true);
        btn4SearchYear.setEnabled(true);
        
        TextField3Manufacturers.setEnabled(false);
        btn3SearchManufacturers.setEnabled(false);
        TextField5MinSeats.setEnabled(false);
        TextField5MaxSeats.setEnabled(false);
        btn5SearchSeats.setEnabled(false);
        TextField7model.setEnabled(false);
        btn7SearchModel.setEnabled(false);
        TextField10City.setEnabled(false);
        btn10SearchCity.setEnabled(false);
        TextField6SerialNo.setEnabled(false);
        btn6SearchSerialNo.setEnabled(false);
    }//GEN-LAST:event_btn4EnableYearActionPerformed

    private void btn7EnableModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7EnableModelActionPerformed
        // TODO add your handling code here:
        TextField7model.setEnabled(true);
        btn7SearchModel.setEnabled(true);
        
        TextField3Manufacturers.setEnabled(false);
        btn3SearchManufacturers.setEnabled(false);
        TextField5MaxSeats.setEnabled(false);
        TextField5MinSeats.setEnabled(false);
        btn5SearchSeats.setEnabled(false);
        TextField4year.setEnabled(false);
        btn4SearchYear.setEnabled(false);
        TextField10City.setEnabled(false);
        btn10SearchCity.setEnabled(false);
        TextField6SerialNo.setEnabled(false);
        btn6SearchSerialNo.setEnabled(false);
    }//GEN-LAST:event_btn7EnableModelActionPerformed

    private void btn10EnableCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10EnableCityActionPerformed
        // TODO add your handling code here:
        TextField10City.setEnabled(true);
        btn10SearchCity.setEnabled(true);
        
        TextField3Manufacturers.setEnabled(false);
        btn3SearchManufacturers.setEnabled(false);
        TextField5MaxSeats.setEnabled(false);
        TextField5MinSeats.setEnabled(false);
        btn5SearchSeats.setEnabled(false);
        TextField4year.setEnabled(false);
        btn4SearchYear.setEnabled(false);
        TextField7model.setEnabled(false);
        btn7SearchModel.setEnabled(false);
        TextField6SerialNo.setEnabled(false);
        btn6SearchSerialNo.setEnabled(false);
        
    }//GEN-LAST:event_btn10EnableCityActionPerformed

    private void btn6EnableSerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6EnableSerialNoActionPerformed
        // TODO add your handling code here:
        TextField6SerialNo.setEnabled(true);
        btn6SearchSerialNo.setEnabled(true);
        
        TextField3Manufacturers.setEnabled(false);
        btn3SearchManufacturers.setEnabled(false);
        TextField5MaxSeats.setEnabled(false);
        TextField5MinSeats.setEnabled(false);
        btn5SearchSeats.setEnabled(false);
        TextField4year.setEnabled(false);
        btn4SearchYear.setEnabled(false);
        TextField7model.setEnabled(false);
        btn7SearchModel.setEnabled(false);
        TextField10City.setEnabled(false);
        btn10SearchCity.setEnabled(false);
        
    }//GEN-LAST:event_btn6EnableSerialNoActionPerformed

    private void TextField6SerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField6SerialNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField6SerialNoActionPerformed

    private void btn6SearchSerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6SearchSerialNoActionPerformed
        // TODO add your handling code here:
        String Avset;
        int i=0;
        
        try{
            Integer.parseInt(TextField6SerialNo.getText());
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please type a number for Sr. No.!");
            return;
        }
        
        for(Car car : carList){
            if(car.getSerial_num()==Integer.parseInt(TextField6SerialNo.getText())){
                if(car.isAvailable())
                    Avset = "Yes";
                else
                    Avset = "No";
                label6SerialNo.setText("Sr. No: " + car.getSerial_num() + "  |  Brand: " + car.getBrand() + "  |  Model: " + car.getModel_num() + "  |  City: " + car.getAvailble_city() + "  |  Available: " + Avset);
                break;
            }
            i++;
        }
        if(i>=carList.size())
            JOptionPane.showMessageDialog(null, "Car Not Found!");
    }//GEN-LAST:event_btn6SearchSerialNoActionPerformed

    private void btn10SearchCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10SearchCityActionPerformed
        // TODO add your handling code here:
        int i = 10;
        FilterResultsJPanel panel = new FilterResultsJPanel(userProcessContainer, carslist, TextField10City.getText(), i);
        userProcessContainer.add("FilterResultsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btn10SearchCityActionPerformed

    private void btn11ExpiredMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ExpiredMCActionPerformed
        // TODO add your handling code here:
        int i = 11;
        FilterResultsJPanel panel = new FilterResultsJPanel(userProcessContainer, carslist, "11", i);
        userProcessContainer.add("FilterResultsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btn11ExpiredMCActionPerformed

    private void btn7SearchModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7SearchModelActionPerformed
        // TODO add your handling code here:
        int i = 7;
        FilterResultsJPanel panel = new FilterResultsJPanel(userProcessContainer, carslist, TextField7model.getText(), i);
        userProcessContainer.add("FilterResultsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btn7SearchModelActionPerformed

    private void btn3SearchManufacturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3SearchManufacturersActionPerformed
        // TODO add your handling code here:
        if(TextField3Manufacturers.getText()==null || TextField3Manufacturers.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter any name of Manufacturer.");
            return;
        }
        int i=3;
        FilterResultsJPanel panel = new FilterResultsJPanel(userProcessContainer, carslist, TextField3Manufacturers.getText(), i);
        userProcessContainer.add("FilterResultsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btn3SearchManufacturersActionPerformed

    private void btn4SearchYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4SearchYearActionPerformed
        // TODO add your handling code here:
        String manufactured_year = TextField4year.getText();
        try{
             Integer.parseInt(manufactured_year);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter Year to search!");
            return;
        }
        if(manufactured_year.length()!=4){
            JOptionPane.showMessageDialog(null, "Enter Year in YYYY format.");
            return;
        }
        
        int i=4;
        FilterResultsJPanel panel = new FilterResultsJPanel(userProcessContainer, carslist, TextField4year.getText(), i);
        userProcessContainer.add("FilterResultsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btn4SearchYearActionPerformed

    private void btn5SearchSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5SearchSeatsActionPerformed
        // TODO add your handling code here:
        String min_seats = TextField5MinSeats.getText();
        try{
             Integer.parseInt(min_seats);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter a number for Minimum Seats!");
            return;
        }
        if(Integer.parseInt(min_seats)>10 || Integer.parseInt(min_seats)<0){
            JOptionPane.showMessageDialog(null, "Minimum Seats should be between 0 and 10");
            return;
        }
        
        String max_seats = TextField5MaxSeats.getText();
        try{
             Integer.parseInt(max_seats);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter a number for Maximum Seats!");
            return;
        }
        if(Integer.parseInt(max_seats) < Integer.parseInt(min_seats)){
            JOptionPane.showMessageDialog(null, "Maximum Seats cannot be less than Minimum seats!");
            return;
        }
        if(Integer.parseInt(max_seats)>10 || Integer.parseInt(max_seats)<0){
            JOptionPane.showMessageDialog(null, "Maximum Seats should be between 0 and 10.");
            return;
        }
        
        int i=5;
        FilterResultsJPanel panel = new FilterResultsJPanel(userProcessContainer, carslist, TextField5MinSeats.getText(), TextField5MaxSeats.getText(), i);
        userProcessContainer.add("FilterResultsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btn5SearchSeatsActionPerformed

    private void btn2AllAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2AllAvailableActionPerformed
        // TODO add your handling code here:
        AllAvailableCarsJPanel panel = new AllAvailableCarsJPanel(userProcessContainer, carslist);
        userProcessContainer.add("AllAvailableCarsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btn2AllAvailableActionPerformed

    private void btn9FleetUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9FleetUpdateActionPerformed
        // TODO add your handling code here:
        TextField5MinSeats.setEnabled(false);
        TextField5MaxSeats.setEnabled(false);
        btn5SearchSeats.setEnabled(false);
        TextField3Manufacturers.setEnabled(false);
        btn3SearchManufacturers.setEnabled(false);
        TextField4year.setEnabled(false);
        btn4SearchYear.setEnabled(false);
        TextField7model.setEnabled(false);
        btn7SearchModel.setEnabled(false);
        TextField10City.setEnabled(false);
        btn10SearchCity.setEnabled(false);
        TextField6SerialNo.setEnabled(false);
        btn6SearchSerialNo.setEnabled(false);
        
        labelFleetUpdate.setText(String.valueOf(carslist.getFleetUpdate()));
    }//GEN-LAST:event_btn9FleetUpdateActionPerformed

    private void btn8AllManufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8AllManufActionPerformed
        // TODO add your handling code here:
        TextField5MinSeats.setEnabled(false);
        TextField5MaxSeats.setEnabled(false);
        btn5SearchSeats.setEnabled(false);
        TextField3Manufacturers.setEnabled(false);
        btn3SearchManufacturers.setEnabled(false);
        TextField4year.setEnabled(false);
        btn4SearchYear.setEnabled(false);
        TextField7model.setEnabled(false);
        btn7SearchModel.setEnabled(false);
        TextField10City.setEnabled(false);
        btn10SearchCity.setEnabled(false);
        TextField6SerialNo.setEnabled(false);
        btn6SearchSerialNo.setEnabled(false);
        
        HashSet<String> hs = new HashSet<>();
        for(Car car : carList){
            hs.add(car.getBrand());
        }
        
        label8AllManufacturers.setText(String.join(", " , hs));
        
    }//GEN-LAST:event_btn8AllManufActionPerformed

    private void TextField5MinSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField5MinSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField5MinSeatsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField10City;
    private javax.swing.JTextField TextField3Manufacturers;
    private javax.swing.JTextField TextField4year;
    private javax.swing.JTextField TextField5MaxSeats;
    private javax.swing.JTextField TextField5MinSeats;
    private javax.swing.JTextField TextField6SerialNo;
    private javax.swing.JTextField TextField7model;
    private javax.swing.JButton btn10EnableCity;
    private javax.swing.JButton btn10SearchCity;
    private javax.swing.JButton btn11ExpiredMC;
    private javax.swing.JButton btn1firstcar;
    private javax.swing.JButton btn2AllAvailable;
    private javax.swing.JButton btn3EnableManufacturers;
    private javax.swing.JButton btn3SearchManufacturers;
    private javax.swing.JButton btn4EnableYear;
    private javax.swing.JButton btn4SearchYear;
    private javax.swing.JButton btn5EnableSeats;
    private javax.swing.JButton btn5SearchSeats;
    private javax.swing.JButton btn6EnableSerialNo;
    private javax.swing.JButton btn6SearchSerialNo;
    private javax.swing.JButton btn7EnableModel;
    private javax.swing.JButton btn7SearchModel;
    private javax.swing.JButton btn8AllManuf;
    private javax.swing.JButton btn9FleetUpdate;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label1firstcar;
    private javax.swing.JLabel label6SerialNo;
    private javax.swing.JLabel label8AllManufacturers;
    private javax.swing.JLabel labelFleetUpdate;
    // End of variables declaration//GEN-END:variables
}
