/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarCatalog;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author TILAK PARMAR
 */
public class ViewCarDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCarDetailsJPanel
     */
    private JPanel userProcessContainer;
    private Car car;
    private CarCatalog carlist;
    ButtonGroup bgroupAvail;
    ButtonGroup bgroupMainCerti;
    public ViewCarDetailsJPanel(JPanel userProcessContainer, CarCatalog carlist, Car car) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.car = car;
        this.carlist=carlist;
        
        bgroupAvail = new ButtonGroup();
        bgroupAvail.add(RadioYes);
        bgroupAvail.add(RadioNo);
        
        bgroupMainCerti = new ButtonGroup();
        bgroupMainCerti.add(RadioExpired);
        bgroupMainCerti.add(RadioNotExpired);
        
        populateCarDetails();
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }
    
    private void populateCarDetails(){
        
        TextFieldBrand.setText(car.getBrand());
        TextFieldCity.setText(car.getAvailble_city());
        TextFieldMaxSeats.setText(String.valueOf(car.getMax_seats()));
        TextFieldMinSeats.setText(String.valueOf(car.getMin_seats()));
        TextFieldModelNo.setText(car.getModel_num());
        TextFieldSerialNo.setText(String.valueOf(car.getSerial_num()));
        TextFieldYear.setText(String.valueOf(car.getManufactured_year()));
        
        if(car.isAvailable())
            RadioYes.setSelected(true);
        else
            RadioNo.setSelected(true);
        
        if(car.isMaintenance_certificate())
            RadioNotExpired.setSelected(true);
        else
            RadioExpired.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        TextFieldCity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        RadioYes = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        RadioNo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        RadioExpired = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        RadioNotExpired = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        TextFieldModelNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextFieldYear = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextFieldMinSeats = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextFieldMaxSeats = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextFieldBrand = new javax.swing.JTextField();
        TextFieldSerialNo = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Is Car Available?:");

        TextFieldCity.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextFieldCity.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("City:");

        RadioYes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        RadioYes.setText("Yes");
        RadioYes.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Maintainence Certificate:");

        RadioNo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        RadioNo.setText("No");
        RadioNo.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Uber Car Details");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Serial Number:");

        RadioExpired.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        RadioExpired.setText("Expired");
        RadioExpired.setEnabled(false);

        btnBack.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        RadioNotExpired.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        RadioNotExpired.setText("Not Expired");
        RadioNotExpired.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Brand:");

        TextFieldModelNo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextFieldModelNo.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Model Number:");

        TextFieldYear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextFieldYear.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Manufactured In (Year):");

        TextFieldMinSeats.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextFieldMinSeats.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Max Seats:");

        TextFieldMaxSeats.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextFieldMaxSeats.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Min Seats:");

        TextFieldBrand.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextFieldBrand.setEnabled(false);

        TextFieldSerialNo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextFieldSerialNo.setEnabled(false);

        btnSave.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RadioYes)
                                .addGap(18, 18, 18)
                                .addComponent(RadioNo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(RadioExpired)
                                        .addGap(18, 18, 18)
                                        .addComponent(RadioNotExpired)))))))
                .addGap(164, 201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(TextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(TextFieldModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addComponent(TextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addComponent(TextFieldMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(TextFieldMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RadioYes)
                        .addComponent(RadioNo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10))
                    .addComponent(TextFieldSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addComponent(TextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel9))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RadioExpired)
                        .addComponent(RadioNotExpired)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        TextFieldBrand.setEnabled(true);
        TextFieldCity.setEnabled(true);
        TextFieldMaxSeats.setEnabled(true);
        TextFieldMinSeats.setEnabled(true);
        TextFieldModelNo.setEnabled(true);
        TextFieldSerialNo.setEnabled(true);
        TextFieldYear.setEnabled(true);
        RadioYes.setEnabled(true);
        RadioNo.setEnabled(true);
        RadioExpired.setEnabled(true);
        RadioNotExpired.setEnabled(true);
        
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String brand = TextFieldBrand.getText();
        if (brand == null || brand.equals("")){
            JOptionPane.showMessageDialog(null, "Brand Name can't be empty!");
            return;
        }
        
        String manufactured_year = TextFieldYear.getText();
        if(manufactured_year.length()!=4){
            JOptionPane.showMessageDialog(null, "Enter Year in YYYY format.");
            return;
        }
            
        try{
             Integer.parseInt(manufactured_year);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please type an Year!");
            return;
        }
        
        String min_seats = TextFieldMinSeats.getText();
        try{
             Integer.parseInt(min_seats);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter a number for Minimum Seats!");
            return;
        }
        if(Integer.parseInt(min_seats)>10 || Integer.parseInt(min_seats)<0){
            JOptionPane.showMessageDialog(null, "Minimum Seats should be between 0 and 10");
            return;
        }
        
        String max_seats = TextFieldMaxSeats.getText();
        try{
             Integer.parseInt(max_seats);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter a number for Maximum Seats!");
            return;
        }
        if(Integer.parseInt(max_seats) < Integer.parseInt(min_seats)){
            JOptionPane.showMessageDialog(null, "Maximum Seats cannot be less than Minimum seats!");
            return;
        }
        if(Integer.parseInt(max_seats)>10 || Integer.parseInt(max_seats)<0){
            JOptionPane.showMessageDialog(null, "Maximum Seats should be between 0 and 10.");
            return;
        }
        
        String serial_num = TextFieldSerialNo.getText();
        try{
             Integer.parseInt(serial_num);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter a number in Sr. No.!");
            return;
        }
        
        if(RadioYes.isSelected()==false && RadioNo.isSelected()==false)
        {
            JOptionPane.showMessageDialog(null, "Please select Availability of your Car");
            return;
        }
        
        if(RadioExpired.isSelected()==false && RadioNotExpired.isSelected()==false)
        {
            JOptionPane.showMessageDialog(null, "Please select the Status of your car's Maintainence Certificate");
            return;
        }
        
        
        car.setAvailable(RadioYes.isSelected());
        car.setBrand(TextFieldBrand.getText());
        car.setManufactured_year(Integer.parseInt(TextFieldYear.getText()));
        car.setMin_seats(Integer.parseInt(TextFieldMinSeats.getText()));
        car.setMax_seats(Integer.parseInt(TextFieldMaxSeats.getText()));
        car.setSerial_num(Integer.parseInt(TextFieldSerialNo.getText()));
        car.setModel_num(TextFieldModelNo.getText());
        car.setAvailble_city(TextFieldCity.getText());
        car.setMaintenance_certificate(RadioNotExpired.isSelected());
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
        JOptionPane.showMessageDialog(null, "Car Details Updated Successfully");
        
        carlist.setFleetUpdate(new Date());
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioExpired;
    private javax.swing.JRadioButton RadioNo;
    private javax.swing.JRadioButton RadioNotExpired;
    private javax.swing.JRadioButton RadioYes;
    private javax.swing.JTextField TextFieldBrand;
    private javax.swing.JTextField TextFieldCity;
    private javax.swing.JTextField TextFieldMaxSeats;
    private javax.swing.JTextField TextFieldMinSeats;
    private javax.swing.JTextField TextFieldModelNo;
    private javax.swing.JTextField TextFieldSerialNo;
    private javax.swing.JTextField TextFieldYear;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
